### PR TITLE
Fix the color of the toolshed

### PR DESCRIPTION
**Pull request by GregMefford**
:trollface:

### CODE REVIEW

**Comment by fhunleth** [comment]
Wouldn't red look better?

**Comment by mobileoverlord** [comment]
I think we should stain it

**Comment by fhunleth** [comment]
Good point. @GregMefford please update your PR to enable stain in the markdown.

**Comment by GregMefford** [comment]
IDK... if we stain it, won't that make it more toxic when we want to dismantle and recycle the materials later?

**Pull request closed without merging**
